data <- read.csv("household_power_consumption.txt", sep = ";")
library(plyr)
data <- mutate(data, datetime = as.POSIXlt(paste(as.character(data$Date), as.character(data$Time), sep = " "), tz = "", format = "%d/%m/%Y %H:%M:%S"))
data <- subset(data, datetime >= as.POSIXlt("2007-02-01 00:00:00", tz = "", format = "%Y-%m-%d %H:%M:%S"))
data <- subset(data, datetime < as.POSIXlt("2007-02-03 00:00:00", tz = "", format = "%Y-%m-%d %H:%M:%S"))
png("plot3.png", width = 480, height = 480)
plot(c(data$datetime, data$datetime, data$datetime), c(data$Sub_metering_1, data$Sub_metering_2, data$Sub_metering_3), pch = "", yaxt = "n", ylab = "Energy sub metering", xlab = "")
lines(data$datetime, data$Sub_metering_1)
lines(data$datetime, data$Sub_metering_2, col = "red")
lines(data$datetime, data$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1,1))
axis(side = 2, at = seq(0, 30, 10))
dev.off()