data <- read.csv("household_power_consumption.txt", sep = ";")
library(plyr)
data <- mutate(data, datetime = as.POSIXlt(paste(as.character(data$Date), as.character(data$Time), sep = " "), tz = "", format = "%d/%m/%Y %H:%M:%S"))
data <- subset(data, datetime >= as.POSIXlt("2007-02-01 00:00:00", tz = "", format = "%Y-%m-%d %H:%M:%S"))
data <- subset(data, datetime < as.POSIXlt("2007-02-03 00:00:00", tz = "", format = "%Y-%m-%d %H:%M:%S"))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
data$Voltage <- as.numeric(as.character(data$Voltage))
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2), mar = c(4, 4, 2, 2))
plot(data$datetime, data$Global_active_power, pch = "", yaxt = "n", xlab = "", ylab = "Global Active Power")
lines(data$datetime, data$Global_active_power)
axis(side = 2, at = seq(0, 6, 2))
with(data, plot(datetime, Voltage, pch = "", yaxt = "n", ylab = "Voltage"))
lines(data$datetime, data$Voltage)
axis(side = 2, at = seq(234, 246, 2))
plot(c(data$datetime, data$datetime, data$datetime), c(data$Sub_metering_1, data$Sub_metering_2, data$Sub_metering_3), pch = "", yaxt = "n", ylab = "Energy sub metering", xlab = "")
lines(data$datetime, data$Sub_metering_1)
lines(data$datetime, data$Sub_metering_2, col = "red")
lines(data$datetime, data$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1,1))
axis(side = 2, at = seq(0, 30, 10))
with(data, plot(datetime, Global_reactive_power, pch = ""))
lines(data$datetime, data$Global_reactive_power)
dev.off()