data <- read.csv("household_power_consumption.txt", sep = ";")
data <- subset(data, Date >= strptime("2007-02-01", "%Y-%m-%d"))
data <- subset(data, Date <= strptime("2007-02-02", "%Y-%m-%d"))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
png("plot1.png", width = 480, height = 480)
hist(data$Global_active_power, breaks = 24, xlim = c(0, 6), xaxt = "n", yaxt = "n", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", col = "red", main = "Global Active Power")
axis(side = 1, at = seq(0, 6, 2))
axis(side = 2, at = seq(0, 1200, 200))
dev.off()